@startuml

autonumber
hide footbox
skinparam ParticipantPadding 20
skinparam BoxPadding 10

title Built-In SRC Payment Handler

actor Consumer as Consumer
participant Merchant as Merchant <<Website>>

box "Web Browser Environment"
  participant "Web Browser" as Browser <<User Agent>>
  participant "Browser Window" as Window <<Browser Window>>
  participant "SRC Payment Handler" as PH <<Built-in>>
end box

participant "SRCI" as SRCI <<Website>>

activate Consumer
activate Merchant
activate Browser

Consumer->Merchant: Checkout Intent
Merchant->Browser: **Payment Request API** Create\n* List of Supported SRC Payment Method URLs\n* Payment Request Data\n     - SRCI URL
note right
  Payment Request gets created providing list of supported
  SRC Payment Methods along with the Payment Request Data

  The Browser uses the Build-in SRC Payment Handler for each
  of the specified supported SRC Payment Methods.

  The SRCI URL provided will be propagated to Build-in
  SRC Payment Handler to get the Window redirected to.
end note
return //Payment Request Reference//

note over Merchant, Browser
  Merchant calls **HasEnrolledInstrument** to check is SRC Payment
  Methods are supported and Consumer can be recognized locally.
end note
group Has Enrolled Instruments
Merchant->Browser: **Payment Request API** HasEnrolledInstrument\n* Payment Request Reference
Browser->PH: **Internal API** HasEnrolledInstrument\n* List of Supported SRC Payment Method URLs\n* Payment Request Data\n     - SRCI URL
activate PH
note left
  Web Browser initiates internal call
  to Built-In SRC Payment Handler.
end note
PH->PH: Check SRC Profile Long-lived Token
note right
  Built-in SRC SRC Payment Handler checks if
  SRC Profile Long-lived Token is present.
  It returns //True// to indicate the Consumer
  can be recognized.
end note
return //True//
Browser-->Merchant: //True//
note right
  //True// indicates that Built-in SRC Payment Handler
  is ready to handle "low friction" checkout.
end note
end group
Merchant->Merchant: Display Pay Button
activate Merchant
Consumer->Merchant: Click Pay Button
deactivate Merchant
note over Merchant, Browser
  Merchant calls **Show** to launch Payment Request flow by the Browser. 
end note
group Show
Merchant->Browser: **Payment Request API** Show\n* Payment Request Reference
note over Browser, PH
  The Built-in SRC Common Payment Handler is able to handle the supported SRC Payment Method and the browser skips the sheet to directly invoke the Built-in SRC Payment Handler.
end note
Browser->PH: **Internal API** Invoke Build-in SRC Payment Handler\n* List of Supported SRC Payment Method URLs\n* Payment Request Data\n     - SRCI URL
activate PH

PH->PH: Get SRC Profile Long-lived Token
note left
    Built-in SRC Payment Handler retrieves the
    SRC Profile Long-Lived Token form the storage.
end note

PH-\Window: Open Window\n* SRCI URL
activate Window
Window->SRCI: Load SRCI Website
activate SRCI
PH->SRCI: **Window.postMessage**: Send Data\n* Payment Request Data\n* SRC Profile Long-lived Token
note left
   Build-in SRC Payment Handler loads SRC Website following provided SRCI URL
   and passes payment request data and SRC Profile Long-Live Token to SRCI.
end note

group Checkout Process
note over SRCI
    SRCI handles the checkout process and returns
    the result back to the Build-in SRC Payment Handler
end note
end group

SRCI-\PH: **Window.postMessage**: Send Result Data\n* Payload / Correlation ID\n* SRC Profile Long-Lived Token
deactivate SRCI
note right
  If user gives consent to be
  remembered by the DCF SRC Profile
  Long-Lived Token is returned
end note
PH-\\Window!!: Close Window
PH->PH: Store SRC Profile Long-lived Token\n* SRC Profile Long-lived Token
note left
    Build-in SRC Payment Handler stores SRC Profile Long-lived
    Token locally, so it can be used at the later stage
    for recognition of the returning Consumer.
end note

PH-->Browser: **Internal API** Result\n* Payload / Correlation ID
deactivate PH
Browser-->Merchant: **Payment Request API** Result\n* Payload / Correlation ID
end group

Merchant-->Consumer: Checkout Completed

@enduml